# This is a numpy.random investigation

# NumPy Package Investigation
# Fundamentals of Data Analystics Project - November 11th 2018

# What is NumPy


NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.
NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

# Explain the use of the "Simple random data" and "Permutations" functions


Simple random data is defined "as subset of a statistical population in which each member of the subset has an equal probability of being chosen". An example of a simple random sample would be the names of 25 employees being chosen out of a hat from a company of 250 employees.

When we require simple random data to be chosen and provided to us we can use the Simple Random Data features of numPy. There are many functions there to chose from depending on what sample is required. This list is taken from the numPy documentation.

rand(d0, d1, …, dn)	Random values in a given shape.
randn(d0, d1, …, dn)	Return a sample (or samples) from the “standard normal” distribution.
randint(low[, high, size, dtype])	Return random integers from low (inclusive) to high (exclusive).
random_integers(low[, high, size])	Random integers of type np.int between low and high, inclusive.
random_sample([size])	Return random floats in the half-open interval [0.0, 1.0).
random([size])	Return random floats in the half-open interval [0.0, 1.0).
ranf([size])	Return random floats in the half-open interval [0.0, 1.0).
sample([size])	Return random floats in the half-open interval [0.0, 1.0).
choice(a[, size, replace, p])	Generates a random sample from a given 1-D array
bytes(length)	Return random bytes.



In [7]:
import numpy as np #importing the numpy package

In [10]:
np.random.rand(4,5) #creating an array that has columns and 5 lines of data using the rand function


array([[0.12139885, 0.46778618, 0.69982077, 0.80745375, 0.75158675],
       [0.07278158, 0.91615798, 0.50941054, 0.65323997, 0.23974396],
       [0.05493753, 0.72001483, 0.24427923, 0.91528606, 0.22237245],
       [0.55881366, 0.22811051, 0.24635127, 0.56011544, 0.81613532]])

In [11]:
# Exaple of using the randint fucnction. This generates random integers from low to high
np.random.randint(2, size=10) #generating a selection of 10 random numbera between 0-2 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

When creating random numbers using this function, it can be expanded to include a number of arrays

In [19]:
np.random.randint(5, size=(2, 4)) # Generate a 2 x 4 array of ints between 0 and 4, inclusive:

array([[3, 3, 3, 3],
       [3, 4, 4, 2]])

Another popular numpy.random function with the simple random data is the random sample. This will return random floats in the half open interval.

In [2]:
import numpy as np

In [3]:
np.random.random_sample((5,)) # askng for 5 random samples 

array([0.02507659, 0.00191883, 0.28761782, 0.63620465, 0.53822947])

#Permutations Function

Permutations are another subset of function within the numpy package within the numpy random function. 